//! Cross-language goldens generated by CPython (`tools/goldens/gen_core_goldens.py`
//! run with the foundation's environment): canonical JSON bytes must equal
//! `rfc8785.dumps`, and the twister must reproduce `random.Random` draw for draw.

use std::path::PathBuf;

use hf_core::canonical::canonical_bytes;
use hf_core::pyrandom::{seed_words_from_decimal, PyRandom, PyRandomState};
use serde_json::Value;

fn golden(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/goldens")
        .join(name);
    serde_json::from_str(&std::fs::read_to_string(&path).expect("golden file"))
        .expect("golden json")
}

fn b64(s: &str) -> Vec<u8> {
    // a tiny base64 decoder so the test needs no extra dependency
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::new();
    let mut buf = 0u32;
    let mut bits = 0;
    for c in s.bytes().filter(|c| *c != b'=') {
        let v = T.iter().position(|t| *t == c).expect("base64 char") as u32;
        buf = (buf << 6) | v;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push(((buf >> bits) & 0xff) as u8);
        }
    }
    out
}

#[test]
fn canonical_bytes_equal_rfc8785() {
    let g = golden("canonical.json");
    let cases = g["cases"].as_array().unwrap();
    assert!(cases.len() >= 8);
    for (i, case) in cases.iter().enumerate() {
        let want = b64(case["canonical_b64"].as_str().unwrap());
        let got = canonical_bytes(&case["value"]).unwrap();
        assert_eq!(
            got,
            want,
            "case {i}: got {:?} want {:?}",
            String::from_utf8_lossy(&got),
            String::from_utf8_lossy(&want)
        );
    }
}

fn u64s(v: &Value) -> Vec<u64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap())
        .collect()
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect()
}

#[test]
fn twister_reproduces_cpython_for_every_seed() {
    let g = golden("pyrandom.json");
    for (seed, entry) in g["seeds"].as_object().unwrap() {
        let mut rng = PyRandom::from_seed_words(&seed_words_from_decimal(seed).unwrap());
        let got: Vec<u64> = (0..16).map(|_| rng.genrand_u32() as u64).collect();
        assert_eq!(got, u64s(&entry["genrand_uint32"]), "seed {seed} genrand");
        let got: Vec<u64> = (0..8).map(|_| rng.getrandbits(5) as u64).collect();
        assert_eq!(got, u64s(&entry["getrandbits_5"]), "seed {seed} bits5");
        let got: Vec<String> = (0..4).map(|_| rng.getrandbits(64).to_string()).collect();
        let want: Vec<String> = entry["getrandbits_64"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        assert_eq!(got, want, "seed {seed} bits64");
        let got: Vec<String> = (0..2).map(|_| rng.getrandbits(100).to_string()).collect();
        let want: Vec<String> = entry["getrandbits_100"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        assert_eq!(got, want, "seed {seed} bits100");
        let got: Vec<u64> = (0..16).map(|_| rng.randrange(40000)).collect();
        assert_eq!(
            got,
            u64s(&entry["randrange_40000"]),
            "seed {seed} randrange"
        );
        let got: Vec<u64> = (0..16).map(|_| rng.randbelow(7)).collect();
        assert_eq!(got, u64s(&entry["randbelow_7"]), "seed {seed} randbelow");
        assert_eq!(
            rng.sample(12, 4),
            usizes(&entry["sample_12_4"]),
            "seed {seed} sample 12/4 (pool)"
        );
        assert_eq!(
            rng.sample(30, 8),
            usizes(&entry["sample_30_8"]),
            "seed {seed} sample 30/8 (pool)"
        );
        assert_eq!(
            rng.sample(85, 8),
            usizes(&entry["sample_85_8"]),
            "seed {seed} sample 85/8 (pool edge)"
        );
        assert_eq!(
            rng.sample(86, 8),
            usizes(&entry["sample_86_8"]),
            "seed {seed} sample 86/8 (set)"
        );
        for (k, want) in entry["sample_40000_8_first_20"]
            .as_array()
            .unwrap()
            .iter()
            .enumerate()
        {
            assert_eq!(
                rng.sample(40000, 8),
                usizes(want),
                "seed {seed} sample 40000/8 #{k}"
            );
        }
        let got: Vec<f64> = (0..8).map(|_| rng.random()).collect();
        let want: Vec<f64> = entry["random_8"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap())
            .collect();
        assert_eq!(got, want, "seed {seed} random()");
        let got: Vec<f64> = (0..8).map(|_| rng.uniform(-1.0, 1.0)).collect();
        let want: Vec<f64> = entry["uniform_m1_1_8"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap())
            .collect();
        assert_eq!(got, want, "seed {seed} uniform(-1, 1)");
        let state = rng.state();
        let want_state = PyRandomState {
            mt: entry["state_after"]["mt"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_u64().unwrap() as u32)
                .collect(),
            index: entry["state_after"]["index"].as_u64().unwrap() as usize,
        };
        assert_eq!(state, want_state, "seed {seed} state");
        let mut resumed = PyRandom::from_state(&state).unwrap();
        let got: Vec<u64> = (0..8).map(|_| resumed.randrange(40000)).collect();
        assert_eq!(
            got,
            u64s(&entry["after_state_randrange_40000"]),
            "seed {seed} after state"
        );
    }
}

#[test]
fn training_draw_replay_matches_the_python_readers() {
    let g = golden("pyrandom.json");
    for (seed, entry) in g["train_draw_replay"].as_object().unwrap() {
        let mut rng = PyRandom::from_seed_words(&seed_words_from_decimal(seed).unwrap());
        let mut counts = std::collections::HashMap::<usize, u64>::new();
        let mut last = Vec::new();
        for update in 0..5000 {
            let batch = rng.sample(40000, 8);
            if update < 3 {
                assert_eq!(
                    batch,
                    usizes(&entry["first_batches"][update]),
                    "seed {seed} batch {update}"
                );
            }
            for i in &batch {
                *counts.entry(*i).or_default() += 1;
            }
            last = batch;
        }
        assert_eq!(last, usizes(&entry["last_batch"]), "seed {seed} last batch");
        assert_eq!(
            counts.len() as u64,
            entry["distinct_seen"].as_u64().unwrap(),
            "seed {seed} distinct"
        );
        let mut histogram = std::collections::BTreeMap::<u64, u64>::new();
        for c in counts.values() {
            *histogram.entry(*c).or_default() += 1;
        }
        let want: std::collections::BTreeMap<u64, u64> = entry["views_histogram"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(k, v)| (k.parse().unwrap(), v.as_u64().unwrap()))
            .collect();
        assert_eq!(histogram, want, "seed {seed} histogram");
    }
}

/// The runner's prefix-nested `train_sample_indices`, in Rust, against Python.
fn train_sample_indices(n: usize, k: usize, base: usize, seed: u128) -> Vec<usize> {
    let k = k.min(n);
    if k <= base {
        let mut v = PyRandom::from_seed(seed).sample(n, k);
        v.sort_unstable();
        return v;
    }
    let head = PyRandom::from_seed(seed).sample(n, base.min(n));
    let taken: std::collections::HashSet<usize> = head.iter().copied().collect();
    let remaining: Vec<usize> = (0..n).filter(|i| !taken.contains(i)).collect();
    let tail_positions = PyRandom::from_seed(seed + 1).sample(remaining.len(), k - head.len());
    let mut v: Vec<usize> = head
        .into_iter()
        .chain(tail_positions.into_iter().map(|p| remaining[p]))
        .collect();
    v.sort_unstable();
    v
}

#[test]
fn prefix_nested_train_sample_matches_python() {
    let g = golden("pyrandom.json");
    let want = &g["train_sample_40000_10000"];
    let got = train_sample_indices(40000, 10000, 5000, 20260912);
    assert_eq!(got.len() as u64, want["count"].as_u64().unwrap());
    assert_eq!(
        got.iter().map(|x| *x as u64).sum::<u64>(),
        want["sum"].as_u64().unwrap()
    );
    assert_eq!(got[..50].to_vec(), usizes(&want["first_50"]));
    assert_eq!(got[got.len() - 50..].to_vec(), usizes(&want["last_50"]));
    let five = train_sample_indices(40000, 5000, 5000, 20260912);
    assert_eq!(five[..50].to_vec(), usizes(&want["first_50_of_5000"]));
}
